//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMonopoly.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boxes
    {
        public int ID { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public double Depth { get; set; }
        public double Weight { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> Pallet { get; set; }
    
        public virtual Pallets Pallets { get; set; }
    }
}
